# Generated by Django 6.0.4 on 2026-04-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0002_anuncio_valor_currency_alter_anuncio_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='valor_currency',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
