# Generated by Django 6.0.4 on 2026-04-23 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0003_remove_anuncio_valor_currency_alter_anuncio_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
